# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-teams
  description: This component is responsible for provisioning all primary user and system roles into the centralized identity account
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component





